# Generated by Django 3.1.2 on 2020-11-13 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201111_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='feature',
        ),
    ]
